<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" />
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title><xsl:value-of select="/rss/channel/title"/> RSS Feed</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 2rem 1rem;
          }
          header {
            margin-bottom: 2rem;
          }
          h1 {
            font-size: 2.5rem;
            margin: 0;
          }
          h2 {
            font-size: 1.8rem;
            margin: 0;
            color: #0066cc;
          }
          a {
            color: #0066cc;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .description {
            margin-top: 1rem;
            font-size: 1.2rem;
            color: #555;
          }
          .item {
            margin-bottom: 2rem;
            padding-bottom: 1rem;
            border-bottom: 1px solid #eee;
          }
          .item-date {
            color: #666;
            font-size: 0.9rem;
            margin-bottom: 0.5rem;
          }
          .categories {
            display: flex;
            flex-wrap: wrap;
            margin-top: 0.5rem;
          }
          .category {
            background-color: #f0f0f0;
            border-radius: 3px;
            padding: 0.2rem 0.5rem;
            margin-right: 0.5rem;
            margin-bottom: 0.5rem;
            font-size: 0.8rem;
            color: #555;
          }
          .info {
            margin-top: 2rem;
            font-size: 0.9rem;
            color: #666;
          }
        </style>
      </head>
      <body>
        <header>
          <h1><xsl:value-of select="/rss/channel/title"/></h1>
          <div class="description">
            <xsl:value-of select="/rss/channel/description"/>
          </div>
          <p>
            <a>
              <xsl:attribute name="href">
                <xsl:value-of select="/rss/channel/link"/>
              </xsl:attribute>
              Visit Website ↗
            </a>
          </p>
        </header>
        <main>
          <xsl:for-each select="/rss/channel/item">
            <div class="item">
              <h2>
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="link"/>
                  </xsl:attribute>
                  <xsl:value-of select="title"/>
                </a>
              </h2>
              <div class="item-date">
                <xsl:value-of select="pubDate"/>
              </div>
              <p><xsl:value-of select="description"/></p>
              <xsl:if test="category">
                <div class="categories">
                  <xsl:for-each select="category">
                    <span class="category">
                      <xsl:value-of select="."/>
                    </span>
                  </xsl:for-each>
                </div>
              </xsl:if>
            </div>
          </xsl:for-each>
        </main>
        <footer class="info">
          <p>This RSS feed is generated by <a href="https://astro.build">Astro</a>.</p>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>